"""Tool setting definitions: MCP, Audio, Image Analysis, Image Generation, Scheduled Task."""

from __future__ import annotations

from src.kernel.schemas.setting import (
    JsonSchema,
    JsonSchemaField,
    SettingCategory,
    SettingType,
)

TOOLS_SETTING_DEFINITIONS: dict[str, dict] = {
    # ============================================
    # Mcp Settings
    # ============================================
    "ENABLE_MCP": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.ENABLE_MCP",
        "default": True,
        "frontend_visible": True,
    },
    "MCP_GLOBAL_CACHE_TTL_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_GLOBAL_CACHE_TTL_SECONDS",
        "default": 900,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_GLOBAL_MAX_ENTRIES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_GLOBAL_MAX_ENTRIES",
        "default": 100,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_GLOBAL_INIT_WAIT_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_GLOBAL_INIT_WAIT_SECONDS",
        "default": 5,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "MCP_GLOBAL_WARMUP_CONCURRENCY": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_GLOBAL_WARMUP_CONCURRENCY",
        "default": 5,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "MCP_GLOBAL_WARMUP_MAX_USERS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_GLOBAL_WARMUP_MAX_USERS",
        "default": 100,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "MCP_USER_CACHE_TTL_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_USER_CACHE_TTL_SECONDS",
        "default": 900,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_USER_CACHE_MAX_ENTRIES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_USER_CACHE_MAX_ENTRIES",
        "default": 100,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_POOL_TTL_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_POOL_TTL_SECONDS",
        "default": 900,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_POOL_MAX_CONNECTIONS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_POOL_MAX_CONNECTIONS",
        "default": 100,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "MCP_SERVER_LOAD_CONCURRENCY": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_SERVER_LOAD_CONCURRENCY",
        "default": 4,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "MCP_EFFECTIVE_CONFIG_MAX_SERVERS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_EFFECTIVE_CONFIG_MAX_SERVERS",
        "default": 100,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "MCP_EFFECTIVE_CONFIG_MAX_TOOLS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.MCP_EFFECTIVE_CONFIG_MAX_TOOLS",
        "default": 200,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": False,
    },
    "ENABLE_DEFERRED_TOOL_LOADING": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "mcp",
        "description": "settingDesc.ENABLE_DEFERRED_TOOL_LOADING",
        "default": True,
        "depends_on": "ENABLE_MCP",
        "frontend_visible": True,
    },
    "DEFERRED_TOOL_THRESHOLD": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "deferred",
        "description": "settingDesc.DEFERRED_TOOL_THRESHOLD",
        "default": 20,
        "depends_on": "ENABLE_DEFERRED_TOOL_LOADING",
    },
    "DEFERRED_TOOL_SEARCH_LIMIT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "deferred",
        "description": "settingDesc.DEFERRED_TOOL_SEARCH_LIMIT",
        "default": 25,
        "depends_on": "ENABLE_DEFERRED_TOOL_LOADING",
    },
    "SKILL_PROMPT_DESCRIPTION_THRESHOLD": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "skills",
        "description": "settingDesc.SKILL_PROMPT_DESCRIPTION_THRESHOLD",
        "default": 20,
        "depends_on": "ENABLE_SKILLS",
    },
    # ============================================
    # Audio Transcription Settings
    # ============================================
    "ENABLE_AUDIO_TRANSCRIPTION": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.AUDIO_TRANSCRIPTION,
        "description": "settingDesc.ENABLE_AUDIO_TRANSCRIPTION",
        "default": False,
    },
    "AUDIO_TRANSCRIPTION_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.AUDIO_TRANSCRIPTION,
        "description": "settingDesc.AUDIO_TRANSCRIPTION_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_AUDIO_TRANSCRIPTION",
    },
    "AUDIO_TRANSCRIPTION_BASE_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.AUDIO_TRANSCRIPTION,
        "description": "settingDesc.AUDIO_TRANSCRIPTION_BASE_URL",
        "default": "",
        "depends_on": "ENABLE_AUDIO_TRANSCRIPTION",
    },
    "AUDIO_TRANSCRIPTION_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.AUDIO_TRANSCRIPTION,
        "description": "settingDesc.AUDIO_TRANSCRIPTION_MODEL",
        "default": "gpt-4o-mini-transcribe",
        "depends_on": "ENABLE_AUDIO_TRANSCRIPTION",
    },
    "AUDIO_TRANSCRIPTION_MAX_DOWNLOAD_BYTES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.AUDIO_TRANSCRIPTION,
        "description": "settingDesc.AUDIO_TRANSCRIPTION_MAX_DOWNLOAD_BYTES",
        "default": 52428800,
        "depends_on": "ENABLE_AUDIO_TRANSCRIPTION",
    },
    # ============================================
    # Image Analysis Settings
    # ============================================
    "ENABLE_IMAGE_ANALYSIS": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_analysis",
        "description": "settingDesc.ENABLE_IMAGE_ANALYSIS",
        "default": False,
        "frontend_visible": True,
    },
    "IMAGE_ANALYSIS_MODEL_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_analysis",
        "description": "settingDesc.IMAGE_ANALYSIS_MODEL_ID",
        "default": "",
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
        "frontend_visible": True,
    },
    "IMAGE_ANALYSIS_MAX_ATTEMPTS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_analysis",
        "description": "settingDesc.IMAGE_ANALYSIS_MAX_ATTEMPTS",
        "default": 3,
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
    },
    # ============================================
    # Video Analysis Settings（与图片分析同开关挂载；未配模型回落 IMAGE_ANALYSIS_MODEL_ID）
    # ============================================
    "VIDEO_ANALYSIS_MODEL_ID": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "video_analysis",
        "description": "settingDesc.VIDEO_ANALYSIS_MODEL_ID",
        "default": "",
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
        "frontend_visible": True,
    },
    "VIDEO_ANALYSIS_MAX_ATTEMPTS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "video_analysis",
        "description": "settingDesc.VIDEO_ANALYSIS_MAX_ATTEMPTS",
        "default": 3,
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
    },
    "VIDEO_ANALYSIS_RETRY_DELAY": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "video_analysis",
        "description": "settingDesc.VIDEO_ANALYSIS_RETRY_DELAY",
        "default": 1.0,
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
    },
    "VIDEO_ANALYSIS_MAX_BYTES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "video_analysis",
        "description": "settingDesc.VIDEO_ANALYSIS_MAX_BYTES",
        "default": 52428800,
        "min_value": 1048576,
        "max_value": 209715200,
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
        "frontend_visible": True,
    },
    "IMAGE_ANALYSIS_RETRY_DELAY": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_analysis",
        "description": "settingDesc.IMAGE_ANALYSIS_RETRY_DELAY",
        "default": 1.0,
        "depends_on": "ENABLE_IMAGE_ANALYSIS",
    },
    # ============================================
    # Image Generation Settings
    # ============================================
    "ENABLE_IMAGE_GENERATION": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.ENABLE_IMAGE_GENERATION",
        "default": False,
        "frontend_visible": True,
    },
    "IMAGE_GENERATION_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.IMAGE_GENERATION_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_IMAGE_GENERATION",
    },
    "IMAGE_GENERATION_BASE_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.IMAGE_GENERATION_BASE_URL",
        "default": "https://api.openai.com/v1",
        "depends_on": "ENABLE_IMAGE_GENERATION",
    },
    "IMAGE_GENERATION_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.IMAGE_GENERATION_MODEL",
        "default": "gpt-image-2",
        "depends_on": "ENABLE_IMAGE_GENERATION",
    },
    "IMAGE_GENERATION_MODELS": {
        "type": SettingType.JSON,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.IMAGE_GENERATION_MODELS",
        "default": [],
        "depends_on": "ENABLE_IMAGE_GENERATION",
        "json_schema": JsonSchema(
            type="array",
            item_label="settingDesc.IMAGE_GENERATION_MODEL_ITEM",
            fields=[
                JsonSchemaField(
                    name="name",
                    type="text",
                    label="settingDesc.IMAGE_GENERATION_MODEL_NAME",
                    placeholder="gpt-image-2.5-sunburst",
                    required=True,
                ),
                JsonSchemaField(
                    name="description",
                    type="text",
                    label="settingDesc.IMAGE_GENERATION_MODEL_DESCRIPTION",
                    placeholder="precision model for editing-focused premium work",
                ),
            ],
        ),
    },
    "IMAGE_GENERATION_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "image_generation",
        "description": "settingDesc.IMAGE_GENERATION_TIMEOUT",
        "default": 120,
        "depends_on": "ENABLE_IMAGE_GENERATION",
    },
    # ============================================
    # Scheduled Task Settings
    # ============================================
    "ENABLE_SCHEDULED_TASK": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SCHEDULED_TASK,
        "subcategory": "general",
        "description": "settingDesc.ENABLE_SCHEDULED_TASK",
        "default": False,
        "frontend_visible": True,
    },
    # ============================================
    # Web Search Settings
    # ============================================
    "ENABLE_WEB_SEARCH": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.ENABLE_WEB_SEARCH",
        "default": True,
        "frontend_visible": True,
    },
    "WEB_SEARCH_PROVIDER": {
        "type": SettingType.SELECT,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.WEB_SEARCH_PROVIDER",
        "default": "auto",
        "depends_on": "ENABLE_WEB_SEARCH",
        "frontend_visible": True,
        "options": ["auto", "tavily", "brave", "searxng"],
    },
    "TAVILY_API_KEYS": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.TAVILY_API_KEYS",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_SEARCH",
        "frontend_visible": True,
    },
    "BRAVE_API_KEYS": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.BRAVE_API_KEYS",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_SEARCH",
        "frontend_visible": True,
    },
    "SEARXNG_BASE_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.SEARXNG_BASE_URL",
        "default": "",
        "depends_on": "ENABLE_WEB_SEARCH",
        "frontend_visible": True,
    },
    "SEARXNG_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_search",
        "description": "settingDesc.SEARXNG_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_SEARCH",
        "frontend_visible": True,
    },
    # ============================================
    # Web Fetch Settings
    # ============================================
    "ENABLE_WEB_FETCH": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.ENABLE_WEB_FETCH",
        "default": True,
        "frontend_visible": True,
    },
    "WEB_FETCH_PROVIDER": {
        "type": SettingType.SELECT,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.WEB_FETCH_PROVIDER",
        "default": "auto",
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
        "options": ["auto", "direct", "tavily", "firecrawl", "exa", "jina"],
    },
    "JINA_API_KEYS": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.JINA_API_KEYS",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
    },
    "FIRECRAWL_BASE_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.FIRECRAWL_BASE_URL",
        "default": "",
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
    },
    "FIRECRAWL_API_KEYS": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.FIRECRAWL_API_KEYS",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
    },
    "EXA_API_KEYS": {
        "type": SettingType.STRING,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.EXA_API_KEYS",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
    },
    "WEB_FETCH_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.TOOLS,
        "subcategory": "web_fetch",
        "description": "settingDesc.WEB_FETCH_MAX_CHARS",
        "default": 32768,
        "min_value": 1024,
        "max_value": 262144,
        "depends_on": "ENABLE_WEB_FETCH",
        "frontend_visible": True,
    },
}
